version: "3.9"

services:
  linux:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes: 
      - ./study:/home/study
    container_name: linux-study
    tty: true
    stdin_open: true
