version: "3.9"

services:
  linux:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes: 
      - ./study:/home/study
      - ./nginx-html:/usr/local/nginx/html
    container_name: linux-study
    tty: true
    stdin_open: true
    ports:
      - "80:80"
